# Generated by Django 5.2.1 on 2026-05-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(help_text='The full job description text.')),
                ('resume_text', models.TextField(help_text='The extracted resume text (from textarea or PDF).')),
                ('resume_filename', models.CharField(blank=True, default='', help_text='Original PDF filename, if uploaded.', max_length=255)),
                ('match_score', models.IntegerField(default=0, help_text='Overall match percentage (0–100).')),
                ('matched_skills', models.JSONField(blank=True, default=list, help_text='List of skills found in both JD and resume.')),
                ('missing_skills', models.JSONField(blank=True, default=list, help_text='Skills in JD but absent from resume.')),
                ('summary', models.TextField(blank=True, default='', help_text='Short professional summary written by Gemini.')),
                ('improvements', models.JSONField(blank=True, default=list, help_text='List of actionable improvement suggestions.')),
                ('rewritten_bullets', models.JSONField(blank=True, default=list, help_text='List of {"before": ..., "after": ...} bullet rewrites.')),
                ('ats_keywords', models.JSONField(blank=True, default=list, help_text='Important ATS keywords to include.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
